bleaf:
  comix:
    marumaru:
      base_uri: "http://marumaru.in"
      daily_uri: "http://marumaru.in/c/26"
      title_uri: "http://marumaru.in/c/1"
      password: "qndxkr"
      date_format: "yyyy.MM.dd"
    crawler:
      base_path: "/Users/bleaf/Documents/comix"

spring:
  datasource:
    username: bleaf
    password: bleaf!@#
    url: jdbc:postgresql://bkleaf.asuscomm.com:7654/bleaf
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: win

---

spring:
  profiles: win

bleaf:
  comix:
    crawler:
      base-path: "D:\\Comix\\daily"

---

spring:
  profiles: mac

bleaf:
  comix:
    crawler:
      base-path: "/Users/bleaf/Documents/comix"
