bleaf:
  comix:
    marumaru:
      base_uri: "http://marumaru.in"
      daily_uri: "http://marumaru.in/c/26"
      title_uri: "http://marumaru.in/?r=home&mod=search&x=0&y=0&keyword="
      password: "qndxkr"
      date_format: "yyyy.MM.dd"
      cookies:
        "PHPSESSID": "a6a32f8fe9f014abac1746592dd46d9f"
        #"PHPSESSID": "17e24e6e2ce1f1e002c424483edf01a9"
    crawler:
      base_path: "/Users/bleaf/Documents/comix"
      service_path: "/Users/bleaf/Documents/comix/service"
      image_file_domains:
        - "wasabisyrup"

spring:
  datasource:
    username: bleaf
    password: bleaf!@#
    url: jdbc:postgresql://bkleaf.asuscomm.com:7654/bleaf
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: win

---

spring:
  profiles: win

bleaf:
  comix:
    crawler:
      base_path: "D:\\Comix\\daily"
      service_path: "D:\\Comix\\root"

---

spring:
  profiles: mac

bleaf:
  comix:
    crawler:
      base_path: "/Users/bleaf/Documents/comix"
      service_path: "/Users/bleaf/Documents/comix/service"
