bleaf:
  comix:
    marumaru:
      base_uri: "http://marumaru.in"
      daily_uri: "http://marumaru.in/c/26"
      title_uri: "http://marumaru.in/?r=home&mod=search&x=0&y=0&keyword="
      password: "qndxkr"
      date_format: "yyyy.MM.dd"
      cookies:
#        "PHPSESSID": "a6a32f8fe9f014abac1746592dd46d9f"
#        "PHPSESSID": "1b065af1946ded592b3d6f88ece9bdee"
#        "PHPSESSID": "1b065af1946ded592b3d6f88ece9bdee"
        "PHPSESSID": "ujnuhjbubk517htsqgq7mfs663"
    crawler:
      image_file_domains:
        - "wasabisyrup"

spring:
  datasource:
    username: bleaf
    password: bleaf!@#
    url: jdbc:postgresql://bkleaf.asuscomm.com:7654/bleaf
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: mac

server:
  port: 52272

---

spring:
  profiles: win

bleaf:
  comix:
    crawler:
      download_path: "D:\\Comix\\daily"
      service_path: "D:\\Comix\\root"
      timeout: 5000

---

spring:
  profiles: mac

bleaf:
  comix:
    crawler:
      download_path: "/Users/bleaf/Documents/comix"
      service_path: "/Users/bleaf/Documents/comix/service"
      timeout: 5000

---

spring:
  profiles: product

bleaf:
  comix:
    crawler:
      download_path: "/bleaf/comix/download"
      service_path: "/bleaf/comix/service"
      timeout: 30000