bleaf:
  comix:
    marumaru:
      base_uri: "http://marumaru.in"
      daily_uri: "http://marumaru.in/c/26"
      title_uri: "http://marumaru.in/?r=home&mod=search&x=0&y=0&keyword="
      password: "qndxkr"
      date_format: "yyyy.MM.dd"
      cookies:
        "PHPSESSID": "1b065af1946ded592b3d6f88ece9bdee"
        "__cfduid": "d0d9fd9c5362bdfc9003cd91edfd944c51513035507"
        "_ga": "GA1.2.1007799583.1513035505"
        "_gid": "GA1.2.1045165975.1513035505"
        "cf_clearance": "551ed9789e7ff1eee27b77d3b9641e87dc327b4c"
    crawler:
      base_path: "/Users/bleaf/Documents/comix"
      service_path: "/Users/bleaf/Documents/comix/service"
      image_file_domains:
        - "wasabisyrup.com"

spring:
  datasource:
    username: bleaf
    password: bleaf!@#
    url: jdbc:postgresql://bkleaf.asuscomm.com:7654/bleaf
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: mac

---

spring:
  profiles: win

bleaf:
  comix:
    crawler:
      base_path: "D:\\Comix\\daily"
      service_path: "D:\\Comix\\root"

---

spring:
  profiles: mac

bleaf:
  comix:
    crawler:
      base_path: "/Users/bleaf/Documents/comix"
      service_path: "/Users/bleaf/Documents/comix/service"
