bleaf:
  comix:
    marumaru:
      base_uri: "http://marumaru.in"
      daily_uri: "http://marumaru.in/c/26"
      title_uri: "http://marumaru.in/?r=home&mod=search&x=0&y=0&keyword="
      password: "qndxkr"
      date_format: "yyyy.MM.dd"
      cookies:
        "PHPSESSID": "b63cc21aacadec4174200fbe620079ee"
        "__cfduid": "dd657255b4975aec68103765a5830c00d1513085946"
        "_ga": "GA1.2.941182890.1513085949"
        "_gid": "GA1.2.1621272001.1513085949"
        "cf_clearance": "80b4bed1c8614c10951a79f79c468d64d6eae368"
    crawler:
      base_path: "/Users/bleaf/Documents/comix"
      service_path: "/Users/bleaf/Documents/comix/service"
      image_file_domains:
        - "wasabisyrup.com"

spring:
  datasource:
    username: bleaf
    password: bleaf!@#
    url: jdbc:postgresql://bkleaf.asuscomm.com:7654/bleaf
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: win

---

spring:
  profiles: win

bleaf:
  comix:
    crawler:
      base_path: "D:\\Comix\\daily"
      service_path: "D:\\Comix\\root"

---

spring:
  profiles: mac

bleaf:
  comix:
    crawler:
      base_path: "/Users/bleaf/Documents/comix"
      service_path: "/Users/bleaf/Documents/comix/service"
