bleaf:
  comix:
    url:
      marumaru_daily_url: "http://marumaru.in/c/26"
      marumaru_title_url: "http://marumaru.in/c/1"

spring:
  datasource:
    username: bleaf
    password: bleaf!@#
    url: jdbc:postgresql://bkleaf.asuscomm.com:7654/bleaf
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true